name: wananandroid
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # getx
  get: ^4.1.4
  # 屏幕适配
  flutter_screenutil: 5.3.1
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # toast
  fluttertoast: ^8.0.7
  # easyloading
  flutter_easyloading: ^3.0.3
  # 日期
  intl: ^0.18.0
  # http
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  # 缓存
  shared_preferences: ^2.0.5
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.2
  # 加密安全 SHA
  crypto: ^3.0.1
  # webView
  webview_flutter: ^2.0.4
  # loading
  loading_animations: ^2.2.0
  # share
  share: ^2.0.1
  # 设备信息
  device_info: ^2.0.0
  # 包信息
  package_info: ^2.0.0
  # 路径查询
  path_provider: ^2.0.1
  # permission 权限
  permission_handler: ^7.1.0
  # 错误收集
  sentry: ^5.0.0
  # 通过 scheme 打开APP 获取 参数
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    # 加载页面图片资源
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
